apiVersion: vinyl.solidite.fr/v1beta1
kind: Package
metadata:
  app_version: 0.7.8-alpha.4
  category: core
  description: Vynil controller to manage vynil packages installations
  features:
  - upgrade
  - auto_config
  name: vynil
  type: system
images:
  agent:
    registry: docker.io
    repository: sebt3/vynil-agent
  controller:
    registry: docker.io
    repository: sebt3/vynil-operator
  diag:
    registry: docker.io
    repository: sebt3/vynil-server
resources:
  controller:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1Gi
  diag:
    requests:
      cpu: 20m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 256Mi
requirements: []
recommandations:
- custom_resource_definition: servicemonitors.monitoring.coreos.com
- custom_resource_definition: certificates.cert-manager.io
- custom_resource_definition: issuers.cert-manager.io
options:
  diagnostic_expose_packages:
    default: true
    type: boolean
    description: Expose the cluster-wide packages list on the diagnostic API (disable for tenants needing stricter confidentiality).
