apiVersion: vinyl.solidite.fr/v1beta1
images:
  agent:
    registry: docker.io
    repository: sebt3/vynil-agent
  controller:
    registry: docker.io
    repository: sebt3/vynil-operator
kind: Package
metadata:
  app_version: 0.4.5
  category: core
  description: Vynil controller to manage vynil packages installations
  features:
  - upgrade
  - auto_config
  name: vynil
  type: system
resources:
  controller:
    requests:
      cpu: 50m
      memory: 256Mi
